"""
This type stub file was generated by pyright.
"""

import warnings
import numpy as np
import pandas as pd
import scipy as sp
from typing import Dict, List, Tuple
from .util_funcs import _check_bounds, _check_groups, avail_approaches, read_param_file
from .problem import ProblemSpec
from .results import ResultDict

"""A set of utility functions"""
__all__ = ["scale_samples", "read_param_file", "avail_approaches"]
def scale_samples(params: np.ndarray, problem: Dict) -> ndarray[Any, Any]:
    """Scale samples based on specified distribution (defaulting to uniform).

    Adds an entry to the problem specification to indicate samples have been
    scaled to maintain backwards compatibility (`sample_scaled`).

    Parameters
    ----------
    params : np.ndarray,
        numpy array of dimensions `num_params`-by-:math:`N`,
        where :math:`N` is the number of samples
    problem : dictionary,
        SALib problem specification

    Returns
    -------
    np.ndarray, scaled samples
    """
    ...

def extract_group_names(p: Dict) -> Tuple:
    """Get a unique set of the group names.

    Maintains specified order of group names.
    `groups` should be a list of parameter names if groups are not defined.

    Parameters
    ----------
    p : ProblemSpec or Dict

    Returns
    -------
    tuple : names, number of groups
    """
    ...

def compute_groups_matrix(groups: List) -> tuple[NDArray[Any], ArrayLike | Any | tuple[ArrayLike, NDArray[Any]]]:
    """Generate matrix which notes factor membership of groups

    Computes a k-by-g matrix which notes factor membership of groups
    where:
        k is the number of variables (factors)
        g is the number of groups
    Also returns a g-length list of unique group_names whose positions
    correspond to the order of groups in the k-by-g matrix

    Parameters
    ----------
    groups : List
        Group names corresponding to each variable

    Returns
    -------
    tuple
        containing group matrix assigning parameters to
        groups and a list of unique group names
    """
    ...

