import copy
import multiprocessing
import logging
import os
import pickle
from typing import Callable
from functools import partial

import numpy as np
from TorchSisso import Regressor
from SALib import ProblemSpec
from SALib.analyze import sobol as analyzer
from SALib.sample import sobol as sampler
from scipy import interpolate
from sklearn.linear_model import Lars, OrthogonalMatchingPursuit

import UQpy.surrogates as surrogates
import UQpy.sampling as sampling

from cicemok import comsol
from cicemok.configuration import (
    ComsolConfiguration,
    SensitivityConfiguration,
)

PRECOMPUTED_POLYNOMIALS = None

def generate_polynomials(config: SensitivityConfiguration):
    dimension = len(config.distribution.marginals)
    trunc = config.cross_truncation

    alpha = surrogates.PolynomialBasis.calculate_hyperbolic_set(
        dimension, config.order, trunc
    )
    polynomials = generate_expansion_from_alpha(alpha, config.distribution)

    return polynomials


def generate_expansion_from_alpha(
    alpha,
    dist,
):
    dimension = len(dist.marginals)
    basis = surrogates.PolynomialBasis.construct_arbitrary_basis(dimension, dist, alpha)
    polynomials = surrogates.PolynomialBasis(dimension, len(alpha), alpha, basis, dist)

    return polynomials


def curate_none_evaluations(
    evaluations: list[np.ndarray | None], samples: np.ndarray
) -> tuple[np.ndarray, list[np.ndarray]]:
    idxs = [i for i, val in enumerate(evaluations) if val is None]

    if len(idxs) == len(evaluations):
        raise ValueError("All samples failed.")

    if float(len(idxs)) / len(evaluations) > 0.2:
        raise ValueError("More than 20% of runs failed.")

    count = 0
    while idxs:
        closeidx = [
            np.argsort(np.linalg.norm(samples - samples[idx], axis=1))[1 + count]
            for idx in idxs
        ]

        for i, idx in enumerate(idxs):
            evaluations[idx] = evaluations[closeidx[i]]

        idxs = [i for i, val in enumerate(evaluations) if val is None]
        count += 1

    assert all(isinstance(result, np.ndarray) for result in evaluations)
    curated_evaluations: list[np.ndarray] = evaluations  # type: ignore
    times = curated_evaluations[0][:, 0]
    evals = [result[:, 1] for result in curated_evaluations]

    return times, evals


def curate_cutoff_evaluations(
    evaluations: list[np.ndarray], samples: np.ndarray
) -> list[np.ndarray]:
    maxim = max([val.shape[0] for val in evaluations])
    coincidence = [i for i, val in enumerate(evaluations) if val.shape[0] == maxim]
    idxs = [i for i, val in enumerate(evaluations) if val.shape[0] < maxim]

    if len(coincidence) < 2:
        raise ValueError("All samples reached cutoff ahead of time.")

    if float(len(idxs)) / len(evaluations) > 0.2:
        raise ValueError("More than 20% of runs failed.")

    count = 0
    while idxs:
        closeidx = [
            np.argsort(np.linalg.norm(samples - samples[idx], axis=1))[1 + count]
            for idx in idxs
        ]

        for i, idx in enumerate(idxs):
            evaluations[idx] = evaluations[closeidx[i]]

        idxs = [i for i, val in enumerate(evaluations) if len(val) < maxim]
        count += 1

    assert all(isinstance(result, np.ndarray) for result in evaluations)
    assert all(len(val) == maxim for val in evaluations)

    return evaluations


def evaluate_models_pool(pool, samples: np.ndarray, config: ComsolConfiguration):
    samples_pool = [sample for sample in samples.T]

    func = partial(comsol.comsol_worker_pool, config=config)
    results = pool.map(func, samples_pool)

    return results


def pce(samples, evals: list[np.ndarray], config: SensitivityConfiguration):
    polyno = generate_polynomials(config)

    X = polyno.evaluate_basis(samples)
    y = np.asarray(evals)
    uhat = np.linalg.lstsq(X, y, rcond=None)[0]

    return (
        polyno,
        uhat.T,
    )


def precompute_polynomial_bases(
    samples: np.ndarray, config: SensitivityConfiguration
) -> dict:
    """
    Precompute polynomial bases for all (p, q) combinations.

    Parameters
    ----------
    samples : np.ndarray
        The experimental design (nsamples, nfeatures).
    config : SensitivityConfiguration
        Configuration for generating polynomials. This configuration should
        have attributes 'minorder' and 'order' that define the range of p values.

    Returns
    -------
    dict
        A dictionary mapping each (p, q) tuple to a tuple (polynomial, poly_evals)
        where 'polynomial' is the polynomial object generated by generate_polynomials
        and 'poly_evals' is the result of evaluating its basis on the samples.
    """
    precomputed = {}
    q_values = np.linspace(0.5, 1, 5)

    logging.info("Starting precomputation of polynomial bases.")
    for q in q_values:
        for p in range(config.minorder, config.order + 1):
            logging.info(
                f"Precomputing polynomial basis for order p={p} and cross_truncation q={q:.3f}..."
            )
            # Create a local copy of the configuration to avoid side effects
            local_config = copy.deepcopy(config)
            local_config.order = p
            local_config.cross_truncation = q

            polynomial = generate_polynomials(local_config)
            poly_evals = polynomial.evaluate_basis(samples)

            # Determine the cardinality: number of polynomial basis elements
            if poly_evals.ndim > 1:
                cardinality = poly_evals.shape[1]
            else:
                cardinality = len(poly_evals)

            precomputed[(p, q)] = (polynomial, poly_evals)
            logging.info(
                f"Finished precomputation for (p={p}, q={q:.3f}). Cardinality: {cardinality}"
            )

    logging.info("Completed precomputation of polynomial bases.")

    return precomputed


def pq_loo_init_worker(precomputed_polys: dict, event: multiprocessing.Event):
    """
    Initializer for worker processes. Sets a global variable.
    
    Parameters
    ----------
    precomputed_polys : dict
        The precomputed polynomial bases that can be large.
    """
    global PRECOMPUTED_POLYNOMIALS
    PRECOMPUTED_POLYNOMIALS = precomputed_polys
    logging.info(f"Worker (PID {os.getpid()}) initialized with precomputed polynomials.")
    event.set()
    

def pq_loo_worker(i, evaluations, method):
    """
    Worker function to compute the best regression model for a single target.
    
    Parameters
    ----------
    i : int
        The target index.
    evaluations : np.ndarray
        Array of model evaluations of shape (nsamples, ntargets).
    method : Callable
        The regression method that takes (poly_evals, target_data) and returns
        (cveloo, uhat).
        
    Returns
    -------
    tuple
        A tuple (best_polynomial, best_regression) corresponding to target i.
    """
    logging.info(f"Worker started for target {i}")
    cveloo_old = np.inf
    best_regression = None
    best_polynomial = None

    global PRECOMPUTED_POLYNOMIALS
    if PRECOMPUTED_POLYNOMIALS is None:
        logging.error("PRECOMPUTED_POLYNOMIALS is not set in worker!")
        return None, None

    # Iterate over all precomputed (p, q) combinationspq_loo_ini
    for (p, q), (polynomial, poly_evals) in PRECOMPUTED_POLYNOMIALS.items():
        try:
            cveloo, uhat = method(poly_evals, evaluations[:, i])
        except Exception as e:
            logging.exception(f"Error processing target {i} for polynomial (p={p}, q={q}): {e}")
            continue

        if cveloo < cveloo_old:
            cveloo_old = cveloo
            best_regression = uhat
            best_polynomial = polynomial
            logging.info(
                f"Target {i}: Updated: Order {p}, Norm {q:.3f}, Mean-ELOO {cveloo:.4f}, "
                f"Cardinality {np.count_nonzero(uhat)}"
            )
        else:
            logging.info(
                f"Target {i}: Not improved: Order {p}, Norm {q:.3f}, Mean-ELOO {cveloo:.4f}"
            )

    logging.info(f"Worker finished for target {i}")
    return best_polynomial, best_regression


def pq_loo_cv(
    samples: np.ndarray,
    evals: list[np.ndarray],
    config: SensitivityConfiguration,
    method: Callable,
    pool,
):
    """
    Run sparse signal regression with Leave-One-Out Error CV across multiple targets,
    using a precomputed set of polynomial bases for various (p, q) combinations.

    Parameters
    ----------
    samples : np.ndarray
        The experimental design (nsamples, nfeatures).
    evals : list[np.ndarray]
        Model evaluations (nsamples, ntargets).
    config : SensitivityConfiguration
        Configuration for generating the polynomial bases.
    method : Callable
        A regression method that takes (poly_evals, target_data) as inputs and returns
        (cveloo, uhat), where cveloo is the Leave-One-Out error and uhat is the regression
        coefficients or model output.
    pool : multiprocess.Pool
        A multiprocess pool for parallel processing with dill seriallization.

    Returns
    -------
    tuple
        Two lists: the first contains the selected polynomial objects for each target,
        and the second contains the corresponding regression results (e.g., coefficients).
    """
    # Standardize evaluations and extract dimensions
    evaluations = np.asarray(evals)
    n, ntrgt = evaluations.shape
    logging.info(f"REGRESSION: nsamples {n} ntargets: {ntrgt}")

    # Precompute the polynomial bases
    worker = partial(
        pq_loo_worker,
        evaluations=evaluations,
        method=method
    )

    results = pool.map(worker, range(ntrgt))
    best_polynomials, best_regressions = zip(*results)

    return best_polynomials, best_regressions


def fn_loo_cv(
    samples, evals: list[np.ndarray], config: SensitivityConfiguration, method: Callable
):
    """
    This algorithm uses sparse signal regression (LARS, OMP, SP, SISSO) with Leave-One-Out Error CV.
    It uses Forward Neighbors for the best model selection, also minimizing the Leave-One-Out Error
    We follow J. Jakeman's paper 2015

    samples: Experimental design. (nsamples, nfeatures)
    evals: Model evaluations. (nsamples, ntargets)
    config: SensitivityConfiguration class
    """

    evaluations = np.asarray(evals)

    # Problem dimensions
    n = evaluations.shape[0]
    ntrgt = evaluations.shape[1]

    # Initialize basis to have q=1 and a cardinality closest to 10*n
    alpha, polynomial = generate_fn_basis(None, 10 * n, config)
    poly_evals = polynomial(*samples).T

    # Loop over targets
    eloos = [np.inf] * ntrgt
    polynomials = [polynomial] * ntrgt
    fouriers = [0] * ntrgt
    surrogates = [0] * ntrgt
    alphas = [alpha] * ntrgt
    for i in range(ntrgt):
        cvelook, uhatk = method(poly_evals, evaluations[:, i])
        alphak = alphas[i] * uhatk
        polynomialk = polynomials[i] * uhatk
        while cvelook < eloos[i]:
            eloos[i] = cvelook
            polynomials[i] = polynomialk
            alphas[i] = alphak
            fouriers[i] = uhatk
            surrogates[i] = numpoly.sum(polynomialk * uhatk)

            cvelook = np.inf
            alphakt = alphak[:, uhatk != 0]
            for t in range(3):
                new_alpha = generate_fn_basis(alphakt, 1, config)
                alphakt = np.hstack((alphakt, new_alpha))
                polynomialkt = generate_expansion_from_alpha(
                    alphakt, config.distribution, "ttr"
                )
                poly_evalkt = polynomialkt(*samples).T
                cvelookt, uhatkt = method(poly_evalkt, evaluations[:, i])

                if cvelookt < cvelook:
                    cvelook = cvelookt
                    uhatk = uhatkt
                    alphak = alphakt
                    polynomialk = polynomialkt

    pass


def lars_loo_cv(X, y):
    """
    Perform Cross-Validation of LARS sparsity hyperparameters based on Leave-One-Out Error.

    Parameters
    ----------
    X : array-like, shape (n_samples, n_features)
        The measurement (design) matrix.
    y : array-like, shape (n_samples,)
        The target measurements.

    Returns
    -------
    eloo_min : float
        The minimum leave-one-out cross validation error obtained.
    uhat_min : array, shape (n_features,)
        The corresponding coefficient vector (sparse) achieving the minimal LOOCV error.
    """
    N = X.shape[0]

    eloo_min = np.inf
    uhat_min = np.zeros(X.shape[1], dtype=float)
    count_eloo = 0

    lars = Lars(fit_intercept=False, n_nonzero_coefs=N - 1)
    lars.fit(X, y)
    for uhat in lars.coef_path_.T[1:]:
        idnonzero = uhat != 0
        eloo = get_eloo(X[:, idnonzero], uhat[idnonzero], y)

        if eloo_min - eloo < -1e-8:
            count_eloo += 1
        else:
            if count_eloo > 0:
                count_eloo -= 1

            uhat_min = uhat
            eloo_min = eloo

        if count_eloo == 2:
            break

    idnonzero = uhat_min != 0
    uhat_min[idnonzero] = np.linalg.lstsq(X[:, idnonzero], y, rcond=None)[0]
    eloo_min = get_eloo(X[:, idnonzero], uhat_min[idnonzero], y)

    return eloo_min, uhat_min


def omp_loo_cv(X, y):
    """
    Perform Cross-Validation of Orthogonal Matching Pursuit (OMP) sparsity hyperparameters based on Leave-One-Out Error.

    Parameters
    ----------
    X : array-like, shape (n_samples, n_features)
        The measurement (design) matrix.
    y : array-like, shape (n_samples,)
        The target measurements.

    Returns
    -------
    eloo_min : float
        The minimum leave-one-out cross validation error obtained.
    uhat_min : array, shape (n_features,)
        The corresponding coefficient vector (sparse) achieving the minimal LOOCV error.
    """
    N = X.shape[0]
    P = X.shape[1]

    eloo_min = np.inf
    uhat_min = np.zeros(X.shape[1], dtype=float)
    count_eloo = 0

    for K in range(1, min(N - 1, P)):
        omp = OrthogonalMatchingPursuit(fit_intercept=False, n_nonzero_coefs=K, precompute=True)
        omp.fit(X, y)
        uhat = omp.coef_
        idnonzero = uhat != 0
        eloo = get_eloo(X[:, idnonzero], uhat[idnonzero], y)

        if eloo_min - eloo < -1e-8:
            count_eloo += 1
        else:
            if count_eloo > 0:
                count_eloo -= 1

            eloo_min = eloo
            uhat_min = uhat

        if count_eloo == 2:
            break

    return eloo_min, uhat_min


def sp_loo_cv(X, y):
    """
    Perform Cross-Validation of Subspace Pursuit (SP) sparsity hyperparameters based on Leave-One-Out Error.

    Parameters
    ----------
    X : array-like, shape (n_samples, n_features)
        The measurement (design) matrix.
    y : array-like, shape (n_samples,)
        The target measurements.

    Returns
    -------
    eloo_min : float
        The minimum leave-one-out cross validation error obtained.
    uhat_min : array, shape (n_features,)
        The corresponding coefficient vector (sparse) achieving the minimal LOOCV error.
    """

    N = X.shape[0]
    P = X.shape[1]

    eloo_min = np.inf
    uhat_min = np.zeros(X.shape[1], dtype=float)
    count_eloo = 0
    for K in range(min(int(N / 2), int(P / 2)) + 1):
        uhat = subspace_pursuit(K, X, y)

        idnonzero = uhat != 0
        eloo = get_eloo(X[:, idnonzero], uhat[idnonzero], y)

        if eloo_min - eloo < -1e-8:
            count_eloo += 1
        else:
            if count_eloo > 0:
                count_eloo -= 1

            eloo_min = eloo
            uhat_min = uhat

        if count_eloo == 2:
            break

    return eloo_min, uhat_min


def sisso_loo_cv(X, y):
    """
    Perform Cross-Validation of SIS+SO (SISSO) sparsity hyperparameters based on Leave-One-Out Error.

    Parameters
    ----------
    X : array-like, shape (n_samples, n_features)
        The measurement (design) matrix.
    y : array-like, shape (n_samples,)
        The target measurements.

    Returns
    -------
    eloo_min : float
        The minimum leave-one-out cross validation error obtained.
    uhat_min : array, shape (n_features,)
        The corresponding coefficient vector (sparse) achieving the minimal LOOCV error.
    """

    N = X.shape[0]
    P = X.shape[1]

    eloo_min = np.inf
    uhat_min = np.zeros(X.shape[1], dtype=float)
    count_eloo = 0
    for K in range(1, min(N - 1, P)):
        uhat = subspace_pursuit(K, X, y)

        idnonzero = uhat != 0
        eloo = get_eloo(X[:, idnonzero], uhat[idnonzero], y)

        if eloo_min - eloo < -1e-8:
            count_eloo += 1
        else:
            if count_eloo > 0:
                count_eloo -= 1

            eloo_min = eloo
            uhat_min = uhat

        if count_eloo == 2:
            break

    return eloo_min, uhat_min


def subspace_pursuit(K, X, y):
    """
    Subspace Pursuit for sparse recovery using iterative support selection and OLS fitting.

    Parameters
    ----------
    K : int
        Approximate upper bound on the signal sparsity such that K >= s,
        where s is the true sparsity level.
    X : ndarray, shape (n_samples, n_features)
        The measurement (or design) matrix.
    y : ndarray, shape (n_samples,)
        The vector of measurements.

    Returns
    -------
    uhat : ndarray, shape (n_features,)
        The estimated sparse coefficient vector. Coefficients corresponding
        to indices outside the recovered support remain zero.

    Notes
    -----
    This is an implementation inspired by Díaz (2018). It performs an initial support
    selection based on the largest absolute correlations between columns of X and y.
    Then, it iteratively refines the support by:
      1. Computing the residual,
      2. Selecting candidate indices based on correlations with the residual,
      3. Merging this candidate set with the current support,
      4. Solving an OLS problem on the union to estimate coefficients,
      5. Pruning back to K indices with the largest coefficient magnitudes.
    The algorithm stops when the residual norm fails to decrease or a maximum iteration
    count is reached.
    """

    uhat = np.zeros(X.shape[1], dtype=float)
    max_iter = X.shape[1]
    Kp = -K - 1

    # Initial estimation
    x = np.zeros(max_iter)
    corr = np.abs(X.T @ y)
    s0 = np.partition(corr, Kp)
    idk = np.nonzero(corr >= s0[Kp])[0]

    x[idk] = np.linalg.lstsq(X[:, idk], y, rcond=None)[0]
    ur0 = y - X @ x

    iter = 0
    while True:
        corr = np.abs(X.T @ ur0)
        s0 = np.partition(corr, Kp)
        idk2 = np.nonzero(corr >= s0[Kp])[0]
        idk2 = np.union1d(idk, idk2)

        x = np.zeros(max_iter)
        x[idk2] = np.linalg.lstsq(X[:, idk2], y, rcond=None)[0]

        # Updated support estimation
        idk0 = idk
        s0 = np.partition(np.abs(x), Kp)
        idk = np.nonzero(np.abs(x) >= s0[Kp])[0]

        # Update residual
        x = np.zeros(max_iter)
        x[idk] = np.linalg.lstsq(X[:, idk], y, rcond=None)[0]
        ur = y - X @ x

        # Break conditions
        iter += 1
        urhat = np.linalg.norm(ur)
        ur0hat = np.linalg.norm(ur0)
        if urhat >= ur0hat:
            idk = idk0
            ur0 = ur
            break

        if iter == max_iter:
            ur0 = ur
            break

    uhat[idk] = np.linalg.lstsq(X[:, idk], y, rcond=None)[0]

    return uhat


def get_eloo(X, x, y):
    """
    Compute the Leave-One-Out Cross-Validation (LOO-CV) error for an OLS fit.

    Parameters
    ----------
    X : ndarray, shape (n_samples, n_features)
        The observation (or design) matrix used for fitting the model.
    x : ndarray, shape (n_features,)
        The OLS coefficient estimates (i.e., the solution vector from the least-squares fit).
    y : ndarray, shape (n_samples,)
        The vector of model evaluations or target measurements.

    Returns
    -------
    eloo : float
        The normalized leave-one-out error, computed by adjusting the mean squared error
        of the leave-one-out residuals with a correction factor and normalizing by the
        sample variance of y.
    """
    n = y.shape[0]
    # Correction factors
    ATA = X.T @ X
    I_ATA = np.linalg.inv(ATA)
    h = (X @ I_ATA @ X.T).diagonal()
    hi = 1.0 - h

    tpn = float(n) * (1.0 + np.trace(I_ATA)) / (float(n) - float(X.shape[1]))

    # Leave One Out Error
    residual = (y - X @ x) / hi
    errloo = np.mean(residual**2)
    var = np.var(y, ddof=1)
    eloo = tpn * errloo / var

    return eloo


def generate_fn_basis(alpha, N: int, config: SensitivityConfiguration):
    fn_config = copy.deepcopy(config)
    fn_config.cross_truncation = 1.0
    d = fn_config.distribution.lower.shape[0]

    if alpha is None:
        combinations = [abs(count_number_coeffs(p, d, 1.0) - N) for p in range(1, 20)]
        order = combinations.index(min(combinations))
        fn_config.order = order
        alpha, polyno = generate_polynomials(fn_config)

        return alpha, polyno

    II = np.eye(d, d, dtype=int)

    # Calculate all possible forward neighboughrs
    I_NEW = II[np.newaxis, :, :]
    FWD = (I_NEW + alpha.T[:, np.newaxis, :]).reshape(d * alpha.shape[1], d)

    # Get all unique elements that are not already in alpha
    FWD = np.unique(FWD, axis=0)
    mask = ~np.any(np.all(FWD[:, np.newaxis] == alpha.T, axis=2), axis=1)
    FWD_UQ = FWD[mask]

    BWD = FWD_UQ[:, np.newaxis, :] - I_NEW

    comparison = BWD[:, :, np.newaxis, :] == alpha.T[np.newaxis, :, :]
    contained = np.any(np.all(comparison, axis=-1), axis=-1)
    idx = np.where(np.all(contained, axis=1))[0]

    return FWD_UQ[idx].T


def get_analytical_mean(fouriers):
    return np.array([fourier[0] for fourier in fouriers])


def get_analytical_variance(fouriers, alphas):
    return np.array([np.sum(fourier[1:] ** 2) for fourier in fouriers])


def get_analytical_sobol(fouriers, alphas, config: SensitivityConfiguration):
    dimension = len(config.distribution.marginals)
    ntrgt = len(fouriers)
    d_hat = get_analytical_variance(fouriers, alphas)

    sens_t_hat = None
    if config.sobol_total:
        sens_t_hat = np.empty((dimension, d_hat.shape[0]))
        for idx in range(dimension):
            index = [alpha[idx, :] > 0 for alpha in alphas]
            sens_t_hat[idx, :] = [
                np.sum((fouriers[i] * index[i]) ** 2) / d_hat[i] for i in range(ntrgt)
            ]

    sens_m2_hat = None
    if config.sobol_second:
        sens_m2_hat = np.empty((dimension, dimension, d_hat.shape[0]))
        for idx in range(dimension):
            for jdx in range(dimension):
                index = [
                    (idx != jdx)
                    & (alpha[idx, :] > 0)
                    & (alpha[jdx, :] > 0)
                    & (alpha.sum(0) == alpha[idx, :] + alpha[jdx, :])
                    for alpha in alphas
                ]
                sens_m2_hat[idx, jdx, :] = [
                    np.sum((fouriers[i] * index[i]) ** 2) / d_hat[i]
                    for i in range(ntrgt)
                ]

    sens_m_hat = np.empty((dimension, d_hat.shape[0]))
    for idx in range(dimension):
        index = [
            (alpha[idx, :] > 0) & (alpha.sum(0) == alpha[idx, :]) for alpha in alphas
        ]
        sens_m_hat[idx, :] = [
            np.sum((fouriers[i] * index[i]) ** 2) / d_hat[i] for i in range(ntrgt)
        ]

    return sens_t_hat, sens_m2_hat, sens_m_hat


def get_sampling_from_experiment(
    npool: int,
    ncores: int,
    nsamples: int,  # If project = True this is the order of the quadrature
    ninterp: int,
    experiment: ComsolConfiguration,
    config: SensitivityConfiguration,
    exclude: float,
    pool,
    method: str = "pce",
):
    if method == "salib":
        if config.rule != "sobol":
            raise ValueError(
                "'rule' in ComsolConfiguration must be 'sobol' if method = 'salib'"
            )

        sp = {
            "names": experiment.names,
            "bounds": [[-1.0, 1.0]] * len(config.distribution.marginals),
            "num_vars": len(experiment.names),
        }

        samples_q = sampling.LatinHypercubeSampling(
            distributions=config.distribution, nsamples=nsamples
        ).samples
        samples_r = surrogates.Polynomials.standardize_sample(
            samples_q, config.distribution
        )
        problem = sp
    else:
        samples_q = sampling.LatinHypercubeSampling(
            distributions=config.distribution, nsamples=nsamples
        ).samples
        samples_r = surrogates.Polynomials.standardize_sample(
            samples_q, config.distribution
        )
        problem = None

    evals = evaluate_models_pool(pool, samples_q.T, experiment)
    nevb = len(evals)

    # INVERT MIN MAX FUNCTION FOR INCREASING VOLTAGE VALUES (CHARGE)
    check_nones = any(v is None for v in evals)
    logging.info(
        f"EVALUATIONS: Finished {len(evals)} evaluations, Nones -> {check_nones}"
    )
    xinit = min([v[0, 0] for v in evals if v is not None and v[0, 0] > exclude])
    xfin = max([v[-1, 0] for v in evals if v is not None])

    f = [
        (
            interpolate.interp1d(
                v[:, 0], v[:, 1], assume_sorted=False, fill_value="extrapolate"
            )
            if v is not None and v[0, 0] > exclude
            else None
        )
        for v in evals
    ]

    x = np.linspace(xinit, xfin, ninterp)
    ys = [interp(x) if interp is not None else None for interp in f]

    evals = [np.column_stack((x, y)) if y is not None else None for y in ys]
    neva = len(evals)

    if method == "project" and (nevb != neva):
        raise ValueError(
            "You are trying to the spectral projection for failed evaluations in quadrature points"
        )
    if method == "salib" and (nevb != neva):
        raise ValueError(
            "You are trying to use method from SALib with a sobol sampler for failed evaluations"
        )

    x, ys = curate_none_evaluations(evals, samples_r)

    return samples_r, samples_q, x, ys, problem


def get_sa_from_experiment(
    samples,
    y,
    problem,
    config: SensitivityConfiguration,
    pool,
    method: str = "pce",
):
    assert (method == "salib" and problem is not None) or (
        method != "salib" and problem is None
    )

    if method == "pce":
        polyno, fourier = pce(samples, y, config)
        alpha = [polyno.multi_index_set.T for _ in range(len(fourier))]
    elif method == "pq-lars-loo":
        polyno, fourier = pq_loo_cv(samples, y, config, lars_loo_cv, pool)
        alpha = [pol.multi_index_set.T for pol in polyno]
    elif method == "pq-omp-loo":
        polyno, fourier = pq_loo_cv(samples, y, config, omp_loo_cv, pool)
        alpha = [pol.multi_index_set.T for pol in polyno]
    elif method == "pq-sp-loo":
        polyno, fourier = pq_loo_cv(samples, y, config, sp_loo_cv, pool)
        alpha = [pol.multi_index_set.T for pol in polyno]
    elif method == "fn-lars-loo":
        alpha, fourier, surrogate = fn_loo_cv(samples, y, config, lars_loo_cv)
    elif method == "salib":
        if config.rule != "sobol":
            raise ValueError(
                "'rule' in ComsolConfiguration must be 'sobol' if method = 'salib'"
            )
        data = np.array(y).T
        sobol = [
            analyzer.analyze(
                problem,
                d,
                print_to_console=False,
                calc_second_order=config.sobol_second,
            )
            for d in data
        ]
    else:
        raise ValueError(
            "method variable must be 'pce', 'project', 'salib', 'pq-lars-loo', 'pq-sp-loo', or 'fn-lars-loo'"
        )

    if method == "salib":
        return sobol
    else:
        sobol_t, sobol_2, sobol = get_analytical_sobol(fourier, alpha, config)
        return fourier, polyno, alpha, sobol, sobol_2, sobol_t
