"""
This type stub file was generated by pyright.
"""

def setup(parser) -> ArgumentParser:
    ...

def create(cli_parser=...) -> ArgumentParser:
    ...

def run_cli(cli_parser, run_analysis, known_args=...) -> None:
    ...

